config:
  broadcast-to-console: true
  Console-name: "Console"
  allow-self-teleport: false
  teleport-to-center-block: false
  DecimalFormat: "#.##"
  permission-based-warps: true

messages:
  theme:
    primary-color: YELLOW
    accent-color: GOLD
  commands:
    tp:
      1player:
        player: '&eYou''ve teleported to &6%target%&e.'
        target: '&6%player% &eteleported to you.'
        staff: '&7&o[%player%: &eteleported to %target%&7&o]'
      2player:
        player: '&eYou''ve teleported &6%player1% &eto &6%player2%&e.'
        player1: '&eYou were teleported to &6%player2% &eby &6%player%&e.'
        player2: '&6%player1% &ewas teleported to you by &6%player%&e.'
        staff: '&7&o[%player%: &eteleported %player1% to %player2%&7&o]'
      coords:
        self:
          player: '&eYou''ve teleported to &6%coords%&e.'
          staff: '&7&o[%player%: &eteleported to %coords%&7&o]'
        other:
          player: '&eYou''ve teleported &6%player% &eto &6%coords%&e.'
          target: '&6%player% &eteleported you to &6%coords%&e.'
          staff: '&7&o[%player%: &eteleported %target% to %coords%&7&o]'
    tphere:
      player: '&eYou''ve teleported &6%target% &eto &6you&e.'
      target: '&eYou were teleported to &6%player%&e.'
      staff: '&7&o[%player%: &eteleported %target% to %player%&7&o]'
    tpall:
      self:
        player: '&eYou''ve teleported &6all players &eto &6you&e.'
        target: '&eAll players were teleported to &6%player%&e.'
        staff: '&7&o[%player%: &eteleported all players to %player%&7&o]'
      other:
        player: '&eYou''ve teleported all players to &6%target%&e.'
        target: '&eAll players were teleported to &6%player%&e.'
        staff: '&7&o[%player%: &eteleported all players to %target%&7&o]'
      coords:
        player: '&eYou''ve teleported all players to &6%coords%&e.'
        target: '&eAll players were teleported to &6%coords%&e.'
        staff: '&7&o[%player%: &eteleported all players to %coords%&7&o]'
    warp:
      list: "&eWarps: %warps%&e."
      player: "&eYou've been teleported to the warp &6%warp%&e."
      staff: "&7&o[%player%: &ewarped to %warp%&7&o]"
      convert:
        attempting: "&eAttempting to convert warps..."
        converted: "&a%converted% out of %total% warps have been converted."
  errors:
    PlayerNotFound: "&cNo player matching &e%player% &cis connected to this server."
    NoPermission: "&cI'm sorry, but you do not have permission to perform this command."
    PlayersOnly: "&cError: Console may not execute this command."
    SelfTeleport: "&cYou cannot teleport to yourself."
    InvalidWorld: "&cError: That world does not exists."
    WarpNotFound: "&cError: There is no warp named \"%warp%&c\"."
    NoWarpsDefined: "&cError: No warps defined."
    NoWarpsAvailable: "&cError: There are no warps available."
    NoWarpPermission: "&cYou do not have permission to access the warp."
    EssentialsNotFound: "&cError: The dependency Essentials plugin could not be found."