config:
  broadcast-to-console: true

messages:
  theme:
    primary-color: YELLOW
    accent-color: GOLD
  commands:
    tp:
      1player:
        player: '&eYou''ve teleported to &6%target%&e.'
        target: '&6%player% &eteleported to you.'
        staff: '&7&o[%player%: &eteleported to %target%&7&o]'
      2player:
        player: '&eYou''ve teleported &6%player1% &eto &6%player2%&e.'
        player1: '&eYou were teleported to &6%player2% &eby &6%player%&e.'
        player2: '&6%player1% &ewas teleported to you by &6%player%&e.'
        staff: '&7&o[%player%: &eteleported %player1% to %player2%&7&o]'
      coords:
        player: '&eYou''ve teleported to &6%coords%&e.'
        staff: '&7&o[%player%: &eteleported to %coords%&7&o]'
    tphere:
      player: '&eYou''ve teleported &6%target% &eto &6you&e.'
      target: '&eYou were teleported to &6%player%'
      staff: '&7&o[%player%: &eteleported %target% to %player%&7&o]'
    tpall:
      target: '&eAll players were teleported to &6%player%&e.'
      staff: '&7&o[%player%: &eteleported all players to %player%&7&o]'
  errors:
    PlayerNotFound: "&cNo player matching &e%player% &cis connected to this server."
    NoPermission: "&cI'm sorry, but you do not have permission to perform this command."