name: TeleportNotify
version: ${project.version}
main: me.lloyd26.teleportnotify.TeleportNotify
authors: [Lloyd26]
description: Notify users and admins when they teleport.
commands:
  tpnotify:
    description: TeleportNotify main command.
  tp:
    description: Teleport yourself or someone to another player.
    aliases: [teleport]
  tphere:
    description: Teleport a player to your location.
    aliases: [teleporthere]
  tpall:
    description: Teleport all players to your location.
    aliases: [teleportall]
