package me.lloyd26.teleportnotify.utils;

public enum Error {
    PLAYERNOTFOUND,
    NOPERMISSION,
    PLAYERSONLY,
    INVALIDWORLD,
    WARPNOTFOUND,
    NOWARPSDEFINED,
    NOWARPSAVAILABLE,
    NOWARPPERMISSION,
    ESSENTIALSNOTFOUND
}
